models:
  - model_id: 'Qwen/Qwen2.5-VL-32B-Instruct-AWQ'
    base_url: 'http://10.252.25.235:23000/v1'
    api_key: sk-123456
  - model_id: 'Qwen/Qwen2.5-VL-7B-Instruct'
    base_url: 'http://10.252.25.251:8000/v1'
    api_key: sk-123456
  - model_id: './OpenGVLab/InternVL3-38B-AWQ'
    base_url: 'http://10.252.25.235:23333/v1'
    api_key: sk-xxxxxx

output_http_prefix: http://10.252.25.251:8186
